// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.32.1
// source: tunnel_service.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "tunnel";

/** TunnelRegistryRequest is an empty request for getting the registry */
export interface TunnelRegistryRequest {
}

/** TunnelRegistryResponse contains the registry information */
export interface TunnelRegistryResponse {
  proxyBaseUrl: string;
  availableProcesses: TunnelProcessInfo[];
  timestamp: string;
}

/** TunnelProcessInfo represents information about a managed process */
export interface TunnelProcessInfo {
  name: string;
  displayName: string;
  status: string;
  instances: number;
  proxyPath: string;
  repository: string;
  currentPorts: number[];
  services: ServiceDetail[];
  messages: { [key: string]: MessageDetail };
}

export interface TunnelProcessInfo_MessagesEntry {
  key: string;
  value: MessageDetail | undefined;
}

/** ServiceDetail represents a gRPC service with its methods */
export interface ServiceDetail {
  name: string;
  methods: MethodDetail[];
}

/** MethodDetail represents a gRPC method */
export interface MethodDetail {
  name: string;
  inputType: string;
  outputType: string;
}

/** MessageDetail represents a protobuf message schema */
export interface MessageDetail {
  name: string;
  fields: FieldDetail[];
}

/** FieldDetail represents a field in a message */
export interface FieldDetail {
  name: string;
  type: string;
  repeated: boolean;
  number: number;
  optional: boolean;
}

/** TunnelInvokeRequest represents a gRPC method invocation request */
export interface TunnelInvokeRequest {
  /** Process name (e.g., "db_service_local") */
  process: string;
  /** Service name (e.g., "db_service.db_ChiikiMasterService") */
  service: string;
  /** Method name (e.g., "List") */
  method: string;
  /** Request data as JSON string */
  data: string;
}

/** TunnelInvokeResponse represents a gRPC method invocation response */
export interface TunnelInvokeResponse {
  success: boolean;
  /** Response data as JSON string */
  data: string;
  error: string;
}

function createBaseTunnelRegistryRequest(): TunnelRegistryRequest {
  return {};
}

export const TunnelRegistryRequest: MessageFns<TunnelRegistryRequest> = {
  encode(_: TunnelRegistryRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TunnelRegistryRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTunnelRegistryRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): TunnelRegistryRequest {
    return {};
  },

  toJSON(_: TunnelRegistryRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<TunnelRegistryRequest>, I>>(base?: I): TunnelRegistryRequest {
    return TunnelRegistryRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TunnelRegistryRequest>, I>>(_: I): TunnelRegistryRequest {
    const message = createBaseTunnelRegistryRequest();
    return message;
  },
};

function createBaseTunnelRegistryResponse(): TunnelRegistryResponse {
  return { proxyBaseUrl: "", availableProcesses: [], timestamp: "" };
}

export const TunnelRegistryResponse: MessageFns<TunnelRegistryResponse> = {
  encode(message: TunnelRegistryResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.proxyBaseUrl !== "") {
      writer.uint32(10).string(message.proxyBaseUrl);
    }
    for (const v of message.availableProcesses) {
      TunnelProcessInfo.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.timestamp !== "") {
      writer.uint32(26).string(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TunnelRegistryResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTunnelRegistryResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.proxyBaseUrl = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.availableProcesses.push(TunnelProcessInfo.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.timestamp = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TunnelRegistryResponse {
    return {
      proxyBaseUrl: isSet(object.proxyBaseUrl) ? globalThis.String(object.proxyBaseUrl) : "",
      availableProcesses: globalThis.Array.isArray(object?.availableProcesses)
        ? object.availableProcesses.map((e: any) => TunnelProcessInfo.fromJSON(e))
        : [],
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : "",
    };
  },

  toJSON(message: TunnelRegistryResponse): unknown {
    const obj: any = {};
    if (message.proxyBaseUrl !== "") {
      obj.proxyBaseUrl = message.proxyBaseUrl;
    }
    if (message.availableProcesses?.length) {
      obj.availableProcesses = message.availableProcesses.map((e) => TunnelProcessInfo.toJSON(e));
    }
    if (message.timestamp !== "") {
      obj.timestamp = message.timestamp;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TunnelRegistryResponse>, I>>(base?: I): TunnelRegistryResponse {
    return TunnelRegistryResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TunnelRegistryResponse>, I>>(object: I): TunnelRegistryResponse {
    const message = createBaseTunnelRegistryResponse();
    message.proxyBaseUrl = object.proxyBaseUrl ?? "";
    message.availableProcesses = object.availableProcesses?.map((e) => TunnelProcessInfo.fromPartial(e)) || [];
    message.timestamp = object.timestamp ?? "";
    return message;
  },
};

function createBaseTunnelProcessInfo(): TunnelProcessInfo {
  return {
    name: "",
    displayName: "",
    status: "",
    instances: 0,
    proxyPath: "",
    repository: "",
    currentPorts: [],
    services: [],
    messages: {},
  };
}

export const TunnelProcessInfo: MessageFns<TunnelProcessInfo> = {
  encode(message: TunnelProcessInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.displayName !== "") {
      writer.uint32(18).string(message.displayName);
    }
    if (message.status !== "") {
      writer.uint32(26).string(message.status);
    }
    if (message.instances !== 0) {
      writer.uint32(32).int32(message.instances);
    }
    if (message.proxyPath !== "") {
      writer.uint32(42).string(message.proxyPath);
    }
    if (message.repository !== "") {
      writer.uint32(50).string(message.repository);
    }
    writer.uint32(58).fork();
    for (const v of message.currentPorts) {
      writer.int32(v);
    }
    writer.join();
    for (const v of message.services) {
      ServiceDetail.encode(v!, writer.uint32(66).fork()).join();
    }
    Object.entries(message.messages).forEach(([key, value]) => {
      TunnelProcessInfo_MessagesEntry.encode({ key: key as any, value }, writer.uint32(74).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TunnelProcessInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTunnelProcessInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.displayName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.instances = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.proxyPath = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.repository = reader.string();
          continue;
        }
        case 7: {
          if (tag === 56) {
            message.currentPorts.push(reader.int32());

            continue;
          }

          if (tag === 58) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.currentPorts.push(reader.int32());
            }

            continue;
          }

          break;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.services.push(ServiceDetail.decode(reader, reader.uint32()));
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          const entry9 = TunnelProcessInfo_MessagesEntry.decode(reader, reader.uint32());
          if (entry9.value !== undefined) {
            message.messages[entry9.key] = entry9.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TunnelProcessInfo {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      displayName: isSet(object.displayName) ? globalThis.String(object.displayName) : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      instances: isSet(object.instances) ? globalThis.Number(object.instances) : 0,
      proxyPath: isSet(object.proxyPath) ? globalThis.String(object.proxyPath) : "",
      repository: isSet(object.repository) ? globalThis.String(object.repository) : "",
      currentPorts: globalThis.Array.isArray(object?.currentPorts)
        ? object.currentPorts.map((e: any) => globalThis.Number(e))
        : [],
      services: globalThis.Array.isArray(object?.services)
        ? object.services.map((e: any) => ServiceDetail.fromJSON(e))
        : [],
      messages: isObject(object.messages)
        ? Object.entries(object.messages).reduce<{ [key: string]: MessageDetail }>((acc, [key, value]) => {
          acc[key] = MessageDetail.fromJSON(value);
          return acc;
        }, {})
        : {},
    };
  },

  toJSON(message: TunnelProcessInfo): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.displayName !== "") {
      obj.displayName = message.displayName;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.instances !== 0) {
      obj.instances = Math.round(message.instances);
    }
    if (message.proxyPath !== "") {
      obj.proxyPath = message.proxyPath;
    }
    if (message.repository !== "") {
      obj.repository = message.repository;
    }
    if (message.currentPorts?.length) {
      obj.currentPorts = message.currentPorts.map((e) => Math.round(e));
    }
    if (message.services?.length) {
      obj.services = message.services.map((e) => ServiceDetail.toJSON(e));
    }
    if (message.messages) {
      const entries = Object.entries(message.messages);
      if (entries.length > 0) {
        obj.messages = {};
        entries.forEach(([k, v]) => {
          obj.messages[k] = MessageDetail.toJSON(v);
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TunnelProcessInfo>, I>>(base?: I): TunnelProcessInfo {
    return TunnelProcessInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TunnelProcessInfo>, I>>(object: I): TunnelProcessInfo {
    const message = createBaseTunnelProcessInfo();
    message.name = object.name ?? "";
    message.displayName = object.displayName ?? "";
    message.status = object.status ?? "";
    message.instances = object.instances ?? 0;
    message.proxyPath = object.proxyPath ?? "";
    message.repository = object.repository ?? "";
    message.currentPorts = object.currentPorts?.map((e) => e) || [];
    message.services = object.services?.map((e) => ServiceDetail.fromPartial(e)) || [];
    message.messages = Object.entries(object.messages ?? {}).reduce<{ [key: string]: MessageDetail }>(
      (acc, [key, value]) => {
        if (value !== undefined) {
          acc[key] = MessageDetail.fromPartial(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseTunnelProcessInfo_MessagesEntry(): TunnelProcessInfo_MessagesEntry {
  return { key: "", value: undefined };
}

export const TunnelProcessInfo_MessagesEntry: MessageFns<TunnelProcessInfo_MessagesEntry> = {
  encode(message: TunnelProcessInfo_MessagesEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== undefined) {
      MessageDetail.encode(message.value, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TunnelProcessInfo_MessagesEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTunnelProcessInfo_MessagesEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = MessageDetail.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TunnelProcessInfo_MessagesEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? MessageDetail.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: TunnelProcessInfo_MessagesEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = MessageDetail.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TunnelProcessInfo_MessagesEntry>, I>>(base?: I): TunnelProcessInfo_MessagesEntry {
    return TunnelProcessInfo_MessagesEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TunnelProcessInfo_MessagesEntry>, I>>(
    object: I,
  ): TunnelProcessInfo_MessagesEntry {
    const message = createBaseTunnelProcessInfo_MessagesEntry();
    message.key = object.key ?? "";
    message.value = (object.value !== undefined && object.value !== null)
      ? MessageDetail.fromPartial(object.value)
      : undefined;
    return message;
  },
};

function createBaseServiceDetail(): ServiceDetail {
  return { name: "", methods: [] };
}

export const ServiceDetail: MessageFns<ServiceDetail> = {
  encode(message: ServiceDetail, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    for (const v of message.methods) {
      MethodDetail.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ServiceDetail {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServiceDetail();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.methods.push(MethodDetail.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ServiceDetail {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      methods: globalThis.Array.isArray(object?.methods)
        ? object.methods.map((e: any) => MethodDetail.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ServiceDetail): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.methods?.length) {
      obj.methods = message.methods.map((e) => MethodDetail.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ServiceDetail>, I>>(base?: I): ServiceDetail {
    return ServiceDetail.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServiceDetail>, I>>(object: I): ServiceDetail {
    const message = createBaseServiceDetail();
    message.name = object.name ?? "";
    message.methods = object.methods?.map((e) => MethodDetail.fromPartial(e)) || [];
    return message;
  },
};

function createBaseMethodDetail(): MethodDetail {
  return { name: "", inputType: "", outputType: "" };
}

export const MethodDetail: MessageFns<MethodDetail> = {
  encode(message: MethodDetail, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.inputType !== "") {
      writer.uint32(18).string(message.inputType);
    }
    if (message.outputType !== "") {
      writer.uint32(26).string(message.outputType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MethodDetail {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMethodDetail();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.inputType = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.outputType = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MethodDetail {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      inputType: isSet(object.inputType) ? globalThis.String(object.inputType) : "",
      outputType: isSet(object.outputType) ? globalThis.String(object.outputType) : "",
    };
  },

  toJSON(message: MethodDetail): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.inputType !== "") {
      obj.inputType = message.inputType;
    }
    if (message.outputType !== "") {
      obj.outputType = message.outputType;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MethodDetail>, I>>(base?: I): MethodDetail {
    return MethodDetail.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MethodDetail>, I>>(object: I): MethodDetail {
    const message = createBaseMethodDetail();
    message.name = object.name ?? "";
    message.inputType = object.inputType ?? "";
    message.outputType = object.outputType ?? "";
    return message;
  },
};

function createBaseMessageDetail(): MessageDetail {
  return { name: "", fields: [] };
}

export const MessageDetail: MessageFns<MessageDetail> = {
  encode(message: MessageDetail, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    for (const v of message.fields) {
      FieldDetail.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MessageDetail {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMessageDetail();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.fields.push(FieldDetail.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MessageDetail {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      fields: globalThis.Array.isArray(object?.fields) ? object.fields.map((e: any) => FieldDetail.fromJSON(e)) : [],
    };
  },

  toJSON(message: MessageDetail): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.fields?.length) {
      obj.fields = message.fields.map((e) => FieldDetail.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MessageDetail>, I>>(base?: I): MessageDetail {
    return MessageDetail.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MessageDetail>, I>>(object: I): MessageDetail {
    const message = createBaseMessageDetail();
    message.name = object.name ?? "";
    message.fields = object.fields?.map((e) => FieldDetail.fromPartial(e)) || [];
    return message;
  },
};

function createBaseFieldDetail(): FieldDetail {
  return { name: "", type: "", repeated: false, number: 0, optional: false };
}

export const FieldDetail: MessageFns<FieldDetail> = {
  encode(message: FieldDetail, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.type !== "") {
      writer.uint32(18).string(message.type);
    }
    if (message.repeated !== false) {
      writer.uint32(24).bool(message.repeated);
    }
    if (message.number !== 0) {
      writer.uint32(32).int32(message.number);
    }
    if (message.optional !== false) {
      writer.uint32(40).bool(message.optional);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FieldDetail {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFieldDetail();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.repeated = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.number = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.optional = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FieldDetail {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      repeated: isSet(object.repeated) ? globalThis.Boolean(object.repeated) : false,
      number: isSet(object.number) ? globalThis.Number(object.number) : 0,
      optional: isSet(object.optional) ? globalThis.Boolean(object.optional) : false,
    };
  },

  toJSON(message: FieldDetail): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.repeated !== false) {
      obj.repeated = message.repeated;
    }
    if (message.number !== 0) {
      obj.number = Math.round(message.number);
    }
    if (message.optional !== false) {
      obj.optional = message.optional;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FieldDetail>, I>>(base?: I): FieldDetail {
    return FieldDetail.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FieldDetail>, I>>(object: I): FieldDetail {
    const message = createBaseFieldDetail();
    message.name = object.name ?? "";
    message.type = object.type ?? "";
    message.repeated = object.repeated ?? false;
    message.number = object.number ?? 0;
    message.optional = object.optional ?? false;
    return message;
  },
};

function createBaseTunnelInvokeRequest(): TunnelInvokeRequest {
  return { process: "", service: "", method: "", data: "" };
}

export const TunnelInvokeRequest: MessageFns<TunnelInvokeRequest> = {
  encode(message: TunnelInvokeRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.process !== "") {
      writer.uint32(10).string(message.process);
    }
    if (message.service !== "") {
      writer.uint32(18).string(message.service);
    }
    if (message.method !== "") {
      writer.uint32(26).string(message.method);
    }
    if (message.data !== "") {
      writer.uint32(34).string(message.data);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TunnelInvokeRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTunnelInvokeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.process = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.service = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.method = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.data = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TunnelInvokeRequest {
    return {
      process: isSet(object.process) ? globalThis.String(object.process) : "",
      service: isSet(object.service) ? globalThis.String(object.service) : "",
      method: isSet(object.method) ? globalThis.String(object.method) : "",
      data: isSet(object.data) ? globalThis.String(object.data) : "",
    };
  },

  toJSON(message: TunnelInvokeRequest): unknown {
    const obj: any = {};
    if (message.process !== "") {
      obj.process = message.process;
    }
    if (message.service !== "") {
      obj.service = message.service;
    }
    if (message.method !== "") {
      obj.method = message.method;
    }
    if (message.data !== "") {
      obj.data = message.data;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TunnelInvokeRequest>, I>>(base?: I): TunnelInvokeRequest {
    return TunnelInvokeRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TunnelInvokeRequest>, I>>(object: I): TunnelInvokeRequest {
    const message = createBaseTunnelInvokeRequest();
    message.process = object.process ?? "";
    message.service = object.service ?? "";
    message.method = object.method ?? "";
    message.data = object.data ?? "";
    return message;
  },
};

function createBaseTunnelInvokeResponse(): TunnelInvokeResponse {
  return { success: false, data: "", error: "" };
}

export const TunnelInvokeResponse: MessageFns<TunnelInvokeResponse> = {
  encode(message: TunnelInvokeResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.data !== "") {
      writer.uint32(18).string(message.data);
    }
    if (message.error !== "") {
      writer.uint32(26).string(message.error);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TunnelInvokeResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTunnelInvokeResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.data = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.error = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TunnelInvokeResponse {
    return {
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      data: isSet(object.data) ? globalThis.String(object.data) : "",
      error: isSet(object.error) ? globalThis.String(object.error) : "",
    };
  },

  toJSON(message: TunnelInvokeResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.data !== "") {
      obj.data = message.data;
    }
    if (message.error !== "") {
      obj.error = message.error;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TunnelInvokeResponse>, I>>(base?: I): TunnelInvokeResponse {
    return TunnelInvokeResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TunnelInvokeResponse>, I>>(object: I): TunnelInvokeResponse {
    const message = createBaseTunnelInvokeResponse();
    message.success = object.success ?? false;
    message.data = object.data ?? "";
    message.error = object.error ?? "";
    return message;
  },
};

/** TunnelService provides gRPC-Web endpoints for tunnel management */
export interface TunnelService {
  /** GetRegistry returns the registry of available processes and services */
  GetRegistry(request: TunnelRegistryRequest): Promise<TunnelRegistryResponse>;
  /** InvokeMethod invokes a gRPC method on a managed process */
  InvokeMethod(request: TunnelInvokeRequest): Promise<TunnelInvokeResponse>;
}

export const TunnelServiceServiceName = "tunnel.TunnelService";
export class TunnelServiceClientImpl implements TunnelService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || TunnelServiceServiceName;
    this.rpc = rpc;
    this.GetRegistry = this.GetRegistry.bind(this);
    this.InvokeMethod = this.InvokeMethod.bind(this);
  }
  GetRegistry(request: TunnelRegistryRequest): Promise<TunnelRegistryResponse> {
    const data = TunnelRegistryRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetRegistry", data);
    return promise.then((data) => TunnelRegistryResponse.decode(new BinaryReader(data)));
  }

  InvokeMethod(request: TunnelInvokeRequest): Promise<TunnelInvokeResponse> {
    const data = TunnelInvokeRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "InvokeMethod", data);
    return promise.then((data) => TunnelInvokeResponse.decode(new BinaryReader(data)));
  }
}

/** TunnelService provides gRPC-Web endpoints for tunnel management */
export type TunnelServiceDefinition = typeof TunnelServiceDefinition;
export const TunnelServiceDefinition = {
  name: "TunnelService",
  fullName: "tunnel.TunnelService",
  methods: {
    /** GetRegistry returns the registry of available processes and services */
    getRegistry: {
      name: "GetRegistry",
      requestType: TunnelRegistryRequest,
      requestStream: false,
      responseType: TunnelRegistryResponse,
      responseStream: false,
      options: {},
    },
    /** InvokeMethod invokes a gRPC method on a managed process */
    invokeMethod: {
      name: "InvokeMethod",
      requestType: TunnelInvokeRequest,
      requestStream: false,
      responseType: TunnelInvokeResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
